# Generated by Django 2.2.4 on 2020-01-27 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ru_name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserOldWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField(default=1)),
                ('word_update', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Words')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_words_time', models.DateField(blank=True, null=True)),
                ('bad_words', models.ManyToManyField(blank=True, related_name='user_bad_words', to='words.Words')),
                ('good_words', models.ManyToManyField(blank=True, related_name='user_good_words', to='words.Words')),
                ('new_words', models.ManyToManyField(blank=True, related_name='user_new_words', to='words.Words')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
