# Generated by Django 2.2.4 on 2020-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20200127_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='added_words',
            field=models.ManyToManyField(blank=True, related_name='added_words', to='words.Words'),
        ),
        migrations.AlterField(
            model_name='groupofwords',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
